apiVersion: v1
kind: ServiceAccount
metadata:
  name: voicevox
---
apiVersion: v1
kind: Service
metadata:
  name: voicevox
  labels:
    app: voicevox
    service: voicevox
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 50021
  selector:
    app: voicevox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicevox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voicevox
      version: v1
  template:
    metadata:
      labels:
        app: voicevox
        version: v1
    spec:
      serviceAccountName: voicevox
      containers:
        - name: voicevox
          image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
          resources:
            requests:
              cpu: 4
              memory: 4Gi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50021
