apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: sa
      containers:
        - image: ghcr.io/thr3a/misc-ai:99
          resources: {}
          imagePullPolicy: IfNotPresent
          name: web
          command: ['node', 'server.js']
          # command: ['npm', 'run', 'node-server']
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: my-secret
