apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: growi-data
  name: growi-data
spec:
  storageClassName: nfs-production
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G
