apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  template:
    metadata:
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - image: thr3a/growi-es
        name: elasticsearch
        env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
          value: "true"
        - name: bootstrap.memory_lock
          value: "true"
        resources: {}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-data
