apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongo-configdb
  name: mongo-configdb
spec:
  storageClassName: nfs-production
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
