apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongo-db
  name: mongo-db
spec:
  storageClassName: nfs-production
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
