apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: sa
      containers:
        - image: ghcr.io/thr3a/hatena-blog-shibafu:2
          resources: {}
          imagePullPolicy: IfNotPresent
          name: web
          ports:
            - containerPort: 9292
          envFrom:
            - secretRef:
                name: my-secret
