apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-namer-sensei
---
apiVersion: v1
kind: Service
metadata:
  name: auto-namer-sensei-svc
spec:
  type: LoadBalancer
  selector:
    app: auto-namer-sensei
  ports:
    - port: 80
      targetPort: 3000
