apiVersion: batch/v1
kind: CronJob
metadata:
  name: description
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-description
              image: ghcr.io/thr3a/auto-twitter-profile-generater:latest
              resources: {}
              command:
                - python
                - description.py
              envFrom:
                - secretRef:
                    name: my-secret
          restartPolicy: Never
