apiVersion: batch/v1
kind: CronJob
metadata:
  name: description
spec:
  schedule: "5 4 1 1 *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-description
              image: ghcr.io/thr3a/auto-twitter-profile-generater:2
              resources: {}
              command:
                - python
                - description.py
              envFrom:
                - secretRef:
                    name: my-secret
          nodeSelector:
            type: ubuntu02
          restartPolicy: Never
