apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
  mycnf: |
    [mysqld]
    innodb_buffer_pool_size=8G
    innodb_log_file_size=2G
