namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.7/manifests/install.yaml
  - gateway.yaml
patches:
  - insecure-patch.yaml
# NOT WORKING!!!!!!!!!!!!!!!!!!!!  
# patchesJson6902:
#   - target:
#       group: apps
#       version: v1
#       kind: Service
#       name: argocd-server
#     patch: |-
#       - op: replace
#         path: /spec/ports/1
#         value: {"name":"grpc","nodePort":32477,"port":443,"protocol":"TCP","targetPort":8080}
